export const createEvent = Object.seal({
	createEventTitle: 'Create Event',
	editEventTitle: 'Edit Event',
	eventName: 'Event Name',
	dateTime: 'Date and Time',
	eventDescription: 'Description',
	rolesTitle: 'Roles',
	optionalDescription: '(Optional)',
	chef: 'Chef',
	shoppingDesignee: 'Shopping Designee',
	createEventBtn: 'CREATE EVENT',
	editEventBtn: 'EDIT EVENT',
	memberLimit: 'Member Limit',
	eventRegisteredConfirmation: 'Event registered successfully',
	eventUpdateConfirmation: 'Event modified successfully',
	eventRegistrationFailure: 'Event registration failed',
	completeAllInputs: 'Please complete all the fields',
	needToHaveCbu: 'You need to have your CBU or alias loaded to be a shopping designee',
	isPrivate: 'The event is private',
	hasPenalization: "Debtor's penalization",
	amountPenalization: 'Penalization amount per day',
	penalizationStartingDate: 'Penalization starting date',
	wrongPenalizationDate: "Penalization starting date must be after the event's date"
});
