export const event = Object.seal({
	transferReceiptLoaded: 'Transfer receipt successfully loaded',
	purchaseReceiptLoaded: 'Purchase receipt successfully loaded',
	transferReceiptFailure: 'Transfer receipt couldn’t be uploaded',
	confirmPayBtn: 'Confirm Payment',
	transferRadioBtn: 'Transfer',
	rejectPayBtn: 'Reject Payment',
	cashRadioBtn: 'Cash',
	payOptTitle: 'Payment Alternatives',
	payTitle: 'Payment Data',
	shoppingDesignee: 'Shopping Designee: ',
	alias: 'Alias: ',
	cbu: 'CBU: ',
	totalPrice: 'Amount to pay: ',
	description: 'Description',
	uploadTransferReceipt: 'Upload Transfer Receipt',
	uploadPurchaseReceipt: 'Upload Purchase Receipt',
	amountLabel: 'Amount',
	validatePaymentTitle: 'Validate Payment',
	downloadText: 'Download Transfer Receipt',
	previewText: 'Preview Transfer Receipt',
	payApprovedSuccessfully: 'Payment approved successfully',
	payApproveFailed: 'There has been an error approving',
	payRejectedSuccessfully: 'Payment rejected successfully',
	payRejectionFailed: 'There has been an error rejecting',
	paidByCashText: 'This user has paid by cash',
	uploadReceiptFirst: 'You have to upload the receipt first',
	errorSubmittingFile: 'There has been an error submitting the file',
	loadingPurchaseError: 'There has been a failure loading the purchase receipt',
	fileSendingError: 'There has been an error sending the file',
	optional: '*Optional',
	descriptionMissing: 'Transfer description is missing',
	privateEvent: 'Private Event',
	amountToBePaid: 'Amount: $',
	linkCopiedToClipboard: 'Info copied to clipboard',
	fastAproveText: "This user hasn't submitted any payment yet, do you want to approve anyway?",
	confirmChangeBtn: 'Confirm Change',
	purchasesMadeTitle: 'Purchases Made',
	assignationsUpdatedSuccessfully: 'Assignments updated successfully',
	errorUpdatingAssignations: 'There has been an error updating assignments'
});
