export const eventHome = Object.seal({
	messageBanner: 'Welcome!',
	newEventButton: 'Create new event',
	incomingEvents: 'Incoming events',
	participationInfoTitle: 'What is FoodSpot?',
	participationInfoDescription:
		'FoodSpot is here to help you better organize your office meals. You can create events for your colleagues to join, choose the chef and the person in charge of the shopping, upload transfer receipts and split the expenses. The organizer will be able to upload purchase receipts and will be able to view and approve payments received. Members will be able to join the event and, once the tickets are uploaded, they will see the total amount to be paid. No matter what your dietary restrictions are, you can clarify them in your profile for the chef to take them into consideration.',
	moreAbout: 'MORE INFO',
	participationStepsTitle: 'Come on, join us to the barbecue',
	participationStepsDescriptionPart1:
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis. unt in culpa qui officia deserunt mollit anim id est laborum',
	participationStepsDescriptionPart2:
		'Joining is super easy! Once logged in you will be able to view the registered events and sign up for one of them. You will also be able to create a new one and assign the roles to carry it out. Remember to always pay your debts, otherwise you will not be able to continue attending.',
	LogInTheApp: {
		title: 'ENTER THE APP',
		description: 'Register and Log in'
	},
	joinToAnBarbecue: {
		title: 'JOIN AN EVENT',
		description: 'Subscribe to an event'
	},
	letsEat: {
		title: "LET'S EAT",
		description: 'Enjoy your meal'
	},
	participateButton: 'I WANT TO JOIN',
	currentParticipants: 'Current Participants: ',
	cook: 'Chef: ',
	participateBtn: 'PARTICIPATE',
	infoBtn: 'INFO',
	available: 'available',
	subscribed: 'subscribed',
	closed: 'closed',
	canceled: 'canceled',
	full: 'full',
	userAddedSuccessfully: 'you have been added to the event successfully',
	userAddingFailure: 'there´s been a failure adding you to the event',
	userRemovedSuccessfully: 'you have been removed to the event successfully',
	userRemovingFailure: 'there´s been a failure removing you to the event',
	userResponsabilityChange: 'you have changed your responsability successfully',
	userResponsabilityFailure: 'there´s been a failure changing su responsability',
	eventDeleted: 'the event has been deleted successfully',
	eventDeletingFailure: 'there´s been a failure deleting the event',
	eventClosed: 'the event has been closed successfully',
	eventOpen: 'the event has been opened successfully',
	eventClosingFailure: 'there´s been a failure closing the event',
	organizationTitle: 'Event Organization',
	date: 'Date: ',
	time: 'Time: ',
	organizer: 'Organizer: ',
	menu: 'Menu/Description',
	inchargeTitle: 'In Charge',
	buyer: 'Shopping Designee: ',
	diners: 'Diners: ',
	deleteEventBtn: 'Delete Event',
	closeEventBtn: 'Close Event',
	reopenEventBtn: 'Re-Open Event',
	meOpt: ' Me',
	emptyOpt: 'Unassigned',
	payBtn: 'Pay',
	modifyPay: 'Pending Aproval Modify Payment',
	unassignAtClosing: 'You cant close an event which doesnt have assign cook or shopping designee',
	needsLogin: 'Needs Login to access to this functionality',
	noLoggedMsg: 'You need to be logged in to access to the event´s info',
	noLoggedMsgParticipate: 'You need to be logged in to access to be part of the event',
	purchasesMade: 'Purchases Made',
	loadPurchase: 'New Purchase Receipt',
	purchaseDeleted: 'Purchase Receipt deleted successfully',
	purchaseDeletedError: 'There was an error deleting the purchase',
	downloadingImageError: 'There was an error downloading the image',
	validateBtn: 'Validate',
	getInto: 'PARTICIPATE',
	getOff: 'QUIT EVENT',
	paidNoti: 'PAID',
	pendingNoti: 'PENDING',
	paymentDataIsNecessary: 'You need to add your alias or cbu in your profile',
	me: ' Me',
	empty: 'Unassigned',
	noSpecialDiet: 'No special diet',
	privateEvent: 'Private Event',
	linkCopiedToClipboard: 'Link copied to clipboard',
	needLoginRedirecting: 'You need to be logged in to access to the event, redirecting to login'
});
