export const eventHome = Object.seal({
	messageBanner: 'Welcome!',
	newEventButton: 'Create new event',
	incomingEvents: 'Incoming events',
	participationInfoTitle: 'What is FoodSpot?',
	participationInfoDescription:
		'FoodSpot is here to help you better organize your office meals. You can create events for your colleagues to join, choose the chef and the person in charge of the shopping, upload transfer receipts, and split the expenses. The organizer will be able to upload purchase receipts and view and approve payments received. Members will be able to join the event and, once the tickets are uploaded, they will see the total amount to be paid. No matter what your dietary restrictions are, you can clarify them in your profile for the chef to take them into consideration.',
	moreAbout: 'MORE INFO',
	participationStepsTitle: 'Come on, join us for the barbecue',
	participationStepsDescriptionPart1:
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
	participationStepsDescriptionPart2:
		'Joining is super easy! Once logged in, you will be able to view the registered events and sign up for one of them. You will also be able to create a new one and assign the roles to carry it out. Remember to always pay your debts; otherwise, you will not be able to continue attending.',
	LogInTheApp: {
		title: 'ENTER THE APP',
		description: 'Register and log in'
	},
	joinToAnBarbecue: {
		title: 'JOIN AN EVENT',
		description: 'Subscribe to an event'
	},
	letsEat: {
		title: "LET'S EAT",
		description: 'Enjoy your meal'
	},
	participateButton: 'I WANT TO JOIN',
	currentParticipants: 'Current Participants: ',
	cook: 'Chef: ',
	participateBtn: 'PARTICIPATE',
	infoBtn: 'INFO',
	available: 'available',
	subscribed: 'subscribed',
	closed: 'closed',
	canceled: 'canceled',
	full: 'full',
	userAddedSuccessfully: 'You have been added to the event successfully',
	userAddingFailure: 'There has been a failure adding you to the event',
	userRemovedSuccessfully: 'You have been removed from the event successfully',
	userRemovingFailure: 'There has been a failure removing you from the event',
	shoppingDesigneeTryingToGetOff: "You can't leave the event if you are a shopping designee",
	userResponsabilityChange: 'You have changed your responsibility successfully',
	userResponsabilityFailure: 'There has been a failure changing your responsibility',
	eventDeleted: 'The event has been deleted successfully',
	eventDeletingFailure: 'There has been a failure deleting the event',
	eventClosed: 'The event has been closed successfully',
	eventReadyForPayment: 'The event is now ready to start the payment process',
	eventOpen: 'The event has been opened successfully',
	eventClosingFailure: 'There has been a failure closing the event',
	eventReadyForPaymentFailure: "There has been a failure enabling the event's payments",
	organizationTitle: 'Event Organization',
	date: 'Date: ',
	time: 'Time: ',
	organizer: 'Organizer: ',
	menu: 'Menu/Description',
	inchargeTitle: 'In Charge',
	buyer: 'Shopping Designee: ',
	diners: 'Diners: ',
	deleteEventBtn: 'Delete Event',
	closeEventBtn: 'Close Event',
	reopenEventBtn: 'Re-Open Event',
	meOpt: ' Me',
	emptyOpt: 'Unassigned',
	assignedOpt: 'Assigned ',
	payBtn: 'Pay',
	modifyPay: 'Pending Approval - Modify Payment',
	unassignAtClosing: "You can't close an event without an assigned chef or shopping designee",
	needsLogin: 'You need to log in to access this functionality',
	noLoggedMsg: "You need to be logged in to access the event's info",
	noLoggedMsgParticipate: 'You need to be logged in to participate in the event',
	purchasesMade: 'Purchases Made',
	loadPurchase: 'New Purchase Receipt',
	purchaseDeleted: 'Purchase receipt deleted successfully',
	purchaseDeletedError: 'There was an error deleting the purchase',
	downloadingImageError: 'There was an error downloading the image',
	validateBtn: 'Validate',
	getInto: 'Participate',
	getOff: 'Quit Event',
	paidNoti: 'PAID',
	pendingNoti: 'PENDING',
	paymentDataIsNecessary: 'You need to add your alias or CBU in your profile',
	me: ' Me',
	empty: 'Unassigned',
	noSpecialDiet: 'No special diet',
	privateEvent: 'Private Event',
	linkCopiedToClipboard: 'Link copied to clipboard',
	needLoginRedirecting: 'You need to be logged in to access the event. Redirecting to login...',
	reviewText: 'Review',
	reviewTexts: 'Reviews',
	noPenalizationAmount: 'None',
	penalizationAmount: 'Penalization',
	penalizationStartDate: 'Penalization Starting Date',
	eventCantBeReadyForPaymentWithoutPurchases: "The event can't be ready for payment without purchases",
	readyForPaymentBtn: 'Ready to Pay',
	sdCanNotRemove: 'You cannot unassign yourself if you have made purchases',
	awaitingNoti: 'AWAITING',
	backBtn: 'BACK'
});
