export const userProfile = Object.seal({
	profileTitle: 'User Profile',
	personalData: 'Personal Data',
	editImg: 'Edit Image',
	cbu: 'CBU',
	alias: 'Alias',
	name: 'Name',
	lastName: 'Last Name',
	specialDietTitle: 'Special Diet',
	veganDiet: 'Are you Vegan?',
	vegetarianDiet: 'Are you Vegetarian?',
	hypertensiveDiet: 'Are you Hypertensive?',
	celiacDiet: 'Are you Celiac?',
	saveBtn: 'SAVE',
	headerWelcome: 'Welcome: ',
	logoutBtn: 'LOGOUT',
	loginBtn: 'LOGIN',
	successMsg: 'Information successfully changed',
	failureMsg: "You couldn't update successfully your information",
	errorTypeFile: 'Profile image must be png, jpeg or jpg type'
});
