export const userProfile = Object.seal({
	profileTitle: 'User Profile',
	personalData: 'Personal Data',
	editImg: 'Edit Image',
	cbu: 'CBU',
	alias: 'Alias',
	name: 'Name',
	lastName: 'Last Name',
	specialDietTitle: 'Special Diet',
	veganDiet: 'Are you Vegan?',
	vegetarianDiet: 'Are you Vegetarian?',
	hypertensiveDiet: 'Are you Hypertensive?',
	celiacDiet: 'Are you Celiac?',
	saveBtn: 'SAVE',
	headerWelcome: 'Welcome: ',
	logoutBtn: 'LOGOUT',
	loginBtn: 'LOGIN',
	successMsg: 'Information successfully changed',
	failureMsg: "You couldn't update your information successfully",
	errorTypeFile: 'Profile image must be of type .png, .jpeg or .jpg',
	notificationsTitle: 'Notifications',
	activateNotifications: 'Activate Notifications',
	personalEmail: 'Personal Email',
	newEventNotification: 'A new event has been created',
	eventComingNotification: 'An event is about to start',
	penalizationStartedNotification: 'Your penalization has started',
	oneWeekDebtorNotification: 'You have been a debtor for a week',
	notificationDescription: 'I want to receive notifications when:',
	invalidEmail: 'The entered email is not valid',
	errorEmailRequired: 'Personal email is required to receive notifications'
});
