export const createEvent = Object.seal({
	createEventTitle: 'Crear Evento',
	editEventTitle: 'Editar Evento',
	eventName: 'Nombre del Evento',
	dateTime: 'Fecha y Hora',
	eventDescription: 'Descripción',
	rolesTitle: 'Roles',
	optionalDescription: '(opcional)',
	chef: 'Cocinero',
	shoppingDesignee: 'Encargado de Compras',
	createEventBtn: 'CREAR EVENTO',
	editEventBtn: 'EDITAR EVENTO',
	memberLimit: 'Límite de Participantes',
	eventUpdateConfirmation: 'Evento modificado exitosamente',
	eventRegisteredConfirmation: 'Evento registrado exitosamente',
	eventRegistrationFailure: 'El registro del evento ha fallado',
	completeAllInputs: 'Por favor, completá todos los campos',
	needToHaveCbu: 'Necesitás cargar Alias o CBU para ser Encargado de Compras',
	isPrivate: 'El evento es privado',
	hasPenalization: 'Penalización por deudor',
	amountPenalization: 'Monto de penalización',
	penalizationStartingDate: 'Día de inicio de la penalización',
	wrongPenalizationDate: 'El día de penalización debe ser posterior al día del evento'
});
