export const eventHome = Object.seal({
	messageBanner: 'Bienvenido!',
	newEventButton: 'Crear nuevo evento',
	incomingEvents: 'Proximos eventos',
	participationInfoTitle: 'Como participar.',
	participationInfoDescription:
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis. Excepteur on proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
	moreAbout: 'MAS SOBRE',
	participationStepsTitle: 'Copate, prendete al asado',
	participationStepsDescriptionPart1:
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis. unt in culpa qui officia deserunt mollit anim id est laborum',
	participationStepsDescriptionPart2:
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis. unt in culpa qui officia deserunt mollit anim id est laborum',
	LogInTheApp: {
		title: 'ENTRA A LA APP',
		description: 'Lorem ipsum dolor sit ame'
	},
	joinToAnBarbecue: {
		title: 'ANOTATE A UN ASADO',
		description: 'Lorem ipsum dolor sit ame'
	},
	letsEat: {
		title: 'Y A COMER',
		description: 'Lorem ipsum dolor sit ame'
	},
	participateButton: 'QUIERO PARTICIPAR',
	currentParticipants: 'Participantes actuales: ',
	cook: 'Asador: ',
	participateBtn: 'PARTICIPAR',
	infoBtn: 'INFO',
	available: 'disponible',
	subscribed: 'subscripto',
	closed: 'cerrado',
	canceled: 'cancelado',
	full: 'lleno',
	userAddedSuccessfully: 'haz sido agregado al evento satisfactoriamente',
	userAddingFailure: 'ha habido un error al agregarte al evento',
	userRemovedSuccessfully: 'haz sido removido del evento satisfactoriamente',
	userRemovingFailure: 'ha habido un error al removerte del evento',
	userResponsabilityChange: 'ha modificado su responsabilidad con exito',
	userResponsabilityFailure: 'ha habido un problema modificado su responsabilidad',
	eventDeleted: 'el evento ha sido eliminado con exito',
	eventDeletingFailure: 'ha habido un error eliminando el evento',
	eventClosed: 'el evento ha sido cerrado con exito',
	eventClosingFailure: 'ha habido un error cerrando el evento',
	organizationTitle: 'Organización',
	date: 'Fecha: ',
	time: 'Hora: ',
	organizer: 'Organizador: ',
	menu: 'Menu/Descripción',
	inchargeTitle: 'A Cargo',
	buyer: 'Compras: ',
	diners: 'Comensales: ',
	deleteEventBtn: 'Eliminar Evento',
	closeEventBtn: 'Cerrar Evento',
	reopenEventBtn: 'Re-Abrir Evento',
	meOpt: 'Yo',
	emptyOpt: 'Sin Asignar',
	payBtn: 'Pagar',
	modifyPay: 'Aprovación Pendiente Modificar Pago',
	unassignAtClosing: 'No puede cerrar un evento si aun no tiene asignados los responsables',
	needsLogin: 'Necesita logearse para acceder a esta funcionalidad',
	noLoggedMsg: 'Necesita estar logeado para acceder al evento',
	noLoggedMsgParticipate: 'Necesita estar logeado para participar del evento',
	purchasesMade: 'Compras Realizadas',
	loadPurchase: 'Cargar Compra',
	purchaseDeleted: 'Recivo eliminado con exito',
	purchaseDeletedError: 'Error al eliminar el recivo',
	downloadingImageError: 'Error al descargar la imagen',
	validateBtn: 'Validar',
	getInto: 'Sumarse',
	getOff: 'Bajarse',
	paidNoti: 'PAGO',
	pendingNoti: 'PENDIENTE',
	paymentDataIsNecessary: 'Necesitas cargar tu cbu o tu alias en tu perfil'

});
