export const event = Object.seal({
	transferReceiptLoaded: 'El recibo de transferencia fue cargado exitosamente',
	purchaseReceiptLoaded: 'El recibo de pago fue cargado exitosamente',
	transferReceiptFailure: 'Ha sucedido un error al cargar su recibo de transferencia',
	confirmPayBtn: 'Confirmar Pago',
	transferRadioBtn: 'Transferencia',
	rejectPayBtn: 'Rechazar Pago',
	cashRadioBtn: 'Efectivo',
	payOptTitle: 'Opciones de Pago',
	payTitle: 'Datos del Pago',
	shoppingDesignee: 'Encargado de compras: ',
	alias: 'Alias: ',
	cbu: 'CBU: ',
	totalPrice: 'Monto a abonar: ',
	description: 'Descripción',
	uploadTransferReceipt: 'Cargar comprobante de pago',
	uploadPurchaseReceipt: 'Cargar comprobante de compra',
	amountLabel: 'Monto',
	validatePaymentTitle: 'Validar Pago',
	downloadText: 'Descargar Recibo',
	previewText: 'Vista Previa del Recibo',
	payApprovedSuccessfully: '¡Se ha aprobado el pago con éxito!',
	payApproveFailed: 'Ha ocurrido un error al aprobar el pago',
	payRejectedSuccessfully: '¡Se ha rechazado el pago!',
	payRejectionFailed: 'Ha ocurrido un error al rechazar el pago',
	paidByCashText: 'Este usuario ha pagado en efectivo',
	uploadReceiptFirst: 'Debés cargar el archivo antes de enviar',
	errorSubmittingFile: 'Ha habido un error al cargar el archivo',
	loadingPurchaseError: 'Ha habido un error al cargar el recibo de compra',
	fileSendingError: 'Ha habido un error al enviar el archivo',
	optional: '*Opcional',
	descriptionMissing: 'Es necesario ingresar una descripción del pago',
	privateEvent: 'Evento Privado',
	linkCopiedToClipboard: 'Información copiada al portapapeles',
	amountToBePaid: 'Cantidad: $',
	fastAproveText: 'Este usuario aún no ha abonado, ¿deseás aprobar de todas formas?',
	confirmChangeBtn: 'Confirmar Cambio',
	purchasesMadeTitle: 'Compras realizadas',
	assignationsUpdatedSuccessfully: 'Asignaciones actualizadas correctamente',
	errorUpdatingAssignations: 'Ocurrió un error al guardar las asignaciones.'
});
