export const eventHome = Object.seal({
	messageBanner: 'Bienvenido!',
	newEventButton: 'Crear nuevo evento',
	incomingEvents: 'Proximos eventos',
	participationInfoTitle: '¿Qué es FoodSpot?',
	participationInfoDescription:
		'FoodSpot llegó para ayudar organizar mejor tus comidas en la oficina. Podés crear eventos para que tus compañeros se sumen, elegir al cocinero y el encargado de las compras, subir comprobantes de transferencias y dividir los gastos. El organizador podrá subir los tickets de compra y podrá ver y aprobar los pagos recibidos. Los miembros podrán sumarse al evento y, una vez cargados los tickets, verán el total a pagar. No importan tus restricciones alimentarias, podés aclararlas en tu perfil para que el cocinero las tenga en consideración.',
	moreAbout: 'MÁS INFORMACIÓN',
	participationStepsTitle: 'Copate, prendete al asado',
	participationStepsDescriptionPart1:
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis. unt in culpa qui officia deserunt mollit anim id est laborum',
	participationStepsDescriptionPart2:
		'Sumarte es super sencillo! Una vez logueado serás capaz de ver los eventos registrados e inscribirte a alguno de estos. También serás capaz de crear uno nuevo y asignar los roles para llevarlo a cabo. Recuerda siempre pagar tus deudas, de lo contrario no podrás seguir asistiendo',
	LogInTheApp: {
		title: 'ENTRA A LA APP',
		description: 'Crea un usuario y loggeate'
	},
	joinToAnBarbecue: {
		title: 'ANOTATE A UN ASADO',
		description: 'Inscríbete a un evento'
	},
	letsEat: {
		title: 'Y A COMER',
		description: 'Disfruta de la comida'
	},
	participateButton: 'QUIERO PARTICIPAR',
	currentParticipants: 'Participantes actuales: ',
	cook: 'Cocinero: ',
	participateBtn: 'PARTICIPAR',
	infoBtn: 'INFO',
	available: 'disponible',
	subscribed: 'subscripto',
	closed: 'cerrado',
	canceled: 'cancelado',
	full: 'lleno',
	userAddedSuccessfully: 'haz sido agregado al evento satisfactoriamente',
	userAddingFailure: 'ha habido un error al agregarte al evento',
	userRemovedSuccessfully: 'haz sido removido del evento satisfactoriamente',
	userRemovingFailure: 'ha habido un error al removerte del evento',
	userResponsabilityChange: 'ha modificado su responsabilidad con exito',
	userResponsabilityFailure: 'ha habido un problema modificado su responsabilidad',
	eventDeleted: 'el evento ha sido eliminado con exito',
	eventDeletingFailure: 'ha habido un error eliminando el evento',
	eventClosed: 'el evento ha sido cerrado con exito',
	eventOpen: 'el evento ha sido abierto con exito',
	eventClosingFailure: 'ha habido un error cerrando el evento',
	organizationTitle: 'Organización',
	date: 'Fecha: ',
	time: 'Hora: ',
	organizer: 'Organizador: ',
	menu: 'Menu/Descripción',
	inchargeTitle: 'A Cargo',
	buyer: 'Compras: ',
	diners: 'Comensales: ',
	deleteEventBtn: 'Eliminar Evento',
	closeEventBtn: 'Cerrar Evento',
	reopenEventBtn: 'Re-Abrir Evento',
	meOpt: 'Yo',
	emptyOpt: 'Sin Asignar',
	payBtn: 'Pagar',
	modifyPay: 'Modificar Pago',
	unassignAtClosing: 'No puede cerrar un evento si aun no tiene asignados los responsables',
	needsLogin: 'Necesita logearse para acceder a esta funcionalidad',
	noLoggedMsg: 'Necesita estar logeado para acceder al evento',
	noLoggedMsgParticipate: 'Necesita estar logeado para participar del evento',
	purchasesMade: 'Compras Realizadas',
	loadPurchase: 'Cargar Compra',
	purchaseDeleted: 'Recivo eliminado con exito',
	purchaseDeletedError: 'Error al eliminar el recivo',
	downloadingImageError: 'Error al descargar la imagen',
	validateBtn: 'Validar',
	getInto: 'Sumarse',
	getOff: 'Bajarse',
	paidNoti: 'PAGO',
	pendingNoti: 'PENDIENTE',
	paymentDataIsNecessary: 'Necesitas cargar tu cbu o tu alias en tu perfil',
	me: ' Yo',
	empty: 'Sin Asignar',
	noSpecialDiet: 'No tiene dieta especial',
	privateEvent: 'Evento Privado',
	linkCopiedToClipboard: 'Link copiado al portapapeles',
	needLoginRedirecting: 'Necesitas estar loggeado para inscribirte al evento, redirigiendo a login',
	reviewText: 'Opinión',
	reviewTexts: 'Opiniones'
});
