export const eventHome = Object.seal({
	messageBanner: '¡Bienvenido!',
	newEventButton: 'Crear nuevo evento',
	incomingEvents: 'Próximos eventos',
	participationInfoTitle: '¿Qué es FoodSpot?',
	participationInfoDescription:
		'FoodSpot llegó para ayudarte a organizar mejor tus comidas en la oficina. Podés crear eventos para que tus compañeros se sumen, elegir al cocinero y al encargado de las compras, subir comprobantes de transferencias y dividir los gastos. El organizador podrá subir los tickets de compra y podrá ver y aprobar los pagos recibidos. Los miembros podrán sumarse al evento y, una vez cargados los tickets, verán el total a pagar. No importan tus restricciones alimentarias, podés aclararlas en tu perfil para que el cocinero las tenga en cuenta.',
	moreAbout: 'MÁS INFORMACIÓN',
	participationStepsTitle: 'Copate, prendete al asado',
	participationStepsDescriptionPart1:
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
	participationStepsDescriptionPart2:
		'¡Sumarte es súper sencillo! Una vez logueado, vas a poder ver los eventos registrados e inscribirte a alguno de ellos. También vas a poder crear uno nuevo y asignar los roles para llevarlo a cabo. Recordá siempre pagar tus deudas; de lo contrario, no vas a poder seguir asistiendo.',
	LogInTheApp: {
		title: 'ENTRÁ A LA APP',
		description: 'Creá un usuario y logueate'
	},
	joinToAnBarbecue: {
		title: 'ANOTATE A UN ASADO',
		description: 'Inscribite a un evento'
	},
	letsEat: {
		title: '¡A COMER!',
		description: 'Disfrutá de la comida'
	},
	participateButton: 'QUIERO PARTICIPAR',
	currentParticipants: 'Participantes actuales: ',
	cook: 'Cocinero: ',
	participateBtn: 'PARTICIPAR',
	infoBtn: 'INFO',
	available: 'disponible',
	subscribed: 'inscripto',
	closed: 'cerrado',
	canceled: 'cancelado',
	full: 'lleno',
	userAddedSuccessfully: 'Has sido agregado al evento exitosamente',
	userAddingFailure: 'Ha habido un error al agregarte al evento',
	userRemovedSuccessfully: 'Has sido removido del evento exitosamente',
	userRemovingFailure: 'Ha habido un error al removerte del evento',
	shoppingDesigneeTryingToGetOff: 'No podés bajarte del evento si sos encargado de las compras',
	userResponsabilityChange: 'Responsabilidad modificada con éxito',
	userResponsabilityFailure: 'Ha habido un error al modificar tu responsabilidad',
	eventDeleted: 'El evento ha sido eliminado con éxito',
	eventDeletingFailure: 'Ha habido un error al eliminar el evento',
	eventClosed: 'El evento ha sido cerrado con éxito',
	eventReadyForPayment: 'El evento está listo para comenzar el proceso de pago',
	eventOpen: 'El evento ha sido abierto con éxito',
	eventClosingFailure: 'Ha habido un error al cerrar el evento',
	eventReadyForPaymentFailure: 'Ha habido un error al habilitar los pagos del evento',
	organizationTitle: 'Organización',
	date: 'Fecha: ',
	time: 'Hora: ',
	organizer: 'Organizador: ',
	menu: 'Menú/Descripción',
	inchargeTitle: 'A Cargo',
	buyer: 'Encargado de compras: ',
	diners: 'Comensales: ',
	deleteEventBtn: 'Eliminar Evento',
	closeEventBtn: 'Cerrar Evento',
	reopenEventBtn: 'Reabrir Evento',
	meOpt: 'Yo',
	emptyOpt: 'Sin asignar',
	assignedOpt: 'Asignado',
	payBtn: 'Pagar',
	modifyPay: 'Modificar Pago',
	unassignAtClosing: 'No se puede cerrar un evento sin responsables asignados',
	needsLogin: 'Necesitás iniciar sesión para acceder a esta funcionalidad',
	noLoggedMsg: 'Necesitás estar logueado para acceder al evento',
	noLoggedMsgParticipate: 'Necesitás estar logueado para participar del evento',
	purchasesMade: 'Compras realizadas',
	loadPurchase: 'Cargar compra',
	purchaseDeleted: 'Recibo eliminado con éxito',
	purchaseDeletedError: 'Error al eliminar el recibo',
	downloadingImageError: 'Error al descargar la imagen',
	validateBtn: 'Validar',
	getInto: 'Sumarse',
	getOff: 'Bajarse',
	paidNoti: 'PAGADO',
	pendingNoti: 'PENDIENTE',
	paymentDataIsNecessary: 'Necesitás cargar tu CBU o tu alias en tu perfil',
	me: 'Yo',
	empty: 'Sin asignar',
	noSpecialDiet: 'Sin dieta especial',
	privateEvent: 'Evento privado',
	linkCopiedToClipboard: 'Link copiado al portapapeles',
	needLoginRedirecting: 'Necesitás estar logueado para inscribirte al evento. Redirigiendo a login...',
	reviewText: 'Opinión',
	reviewTexts: 'Opiniones',
	noPenalizationAmount: 'Sin penalización',
	penalizationAmount: 'Penalización',
	penalizationStartDate: 'Comienzo de penalización',
	eventCantBeReadyForPaymentWithoutPurchases: 'El evento no puede estar listo para el pago sin compras realizadas',
	readyForPaymentBtn: 'Listo para pagar',
	sdCanNotRemove: 'No podés desasignarte si tenés compras registradas',
	awaitingNoti: 'EN ESPERA',
	backBtn: 'VOLVER'
});
