export const userProfile = Object.seal({
	profileTitle: 'Perfil de Usuario',
	personalData: 'Datos Personales',
	editImg: 'Editar Imagen',
	cbu: 'CBU',
	alias: 'Alias',
	name: 'Nombre',
	lastName: 'Apellido',
	specialDietTitle: 'Dieta Especial',
	veganDiet: '¿Sos Vegano?',
	vegetarianDiet: '¿Sos Vegetariano?',
	hypertensiveDiet: '¿Sos Hipertenso?',
	celiacDiet: '¿Sos Celíaco?',
	saveBtn: 'GUARDAR',
	headerWelcome: 'Bienvenido: ',
	logoutBtn: 'SALIR',
	loginBtn: 'INICIAR SESION',
	successMsg: 'La informacion se ha modificado con exito',
	failureMsg: 'Ha habido un problema con la actualizacion de su informacion'
});
