export const userProfile = Object.seal({
	profileTitle: 'Perfil de Usuario',
	personalData: 'Datos Personales',
	editImg: 'Editar Imagen',
	name: 'Nombre',
	email: 'Email',
	cbu: 'CBU',
	alias: 'Alias',
	specialDietTitle: 'Dieta Especial',
	veganDiet: '¿Sos Vegano?',
	vegetarianDiet: '¿Sos Vegetariano?',
	hypertensiveDiet: '¿Sos Hipertenso?',
	celiacDiet: '¿Sos Celíaco?',
	saveBtn: 'GUARDAR',
	headerWelcome: 'Bienvenido: ',
	logoutBtn: 'SALIR',
	loginBtn: 'INICIAR SESION',
	updateSuccessMessage: 'El usuario se actualizo exitosamente',
	updateErrorMessage: 'Actualización de usuario fallida'
});
