export const userProfile = Object.seal({
	profileTitle: 'Perfil de Usuario',
	personalData: 'Datos Personales',
	editImg: 'Editar Imagen',
	cbu: 'CBU',
	alias: 'Alias',
	name: 'Nombre',
	lastName: 'Apellido',
	specialDietTitle: 'Dieta Especial',
	veganDiet: '¿Sos Vegano?',
	vegetarianDiet: '¿Sos Vegetariano?',
	hypertensiveDiet: '¿Sos Hipertenso?',
	celiacDiet: '¿Sos Celíaco?',
	saveBtn: 'GUARDAR',
	headerWelcome: 'Bienvenido: ',
	logoutBtn: 'SALIR',
	loginBtn: 'INICIAR SESIÓN',
	successMsg: 'La información se ha modificado con éxito',
	failureMsg: 'Ha habido un problema con la actualización de tu información',
	errorTypeFile: 'La imagen de perfil debe ser de tipo .png, .jpeg o .jpg',
	notificationsTitle: 'Notificaciones',
	activateNotifications: 'Activar Notificaciones',
	personalEmail: 'Correo Electrónico Personal',
	newEventNotification: 'Un nuevo evento ha sido creado',
	eventComingNotification: 'Un evento está por comenzar',
	penalizationStartedNotification: 'Tu penalización ha comenzado',
	oneWeekDebtorNotification: 'Has sido deudor por una semana',
	notificationDescription: 'Deseo recibir notificaciones cuando:',
	invalidEmail: 'El correo electrónico ingresado no es válido',
	errorEmailRequired: 'El correo electrónico personal es obligatorio para recibir notificaciones'
});
